#include <sys/types.h>
#include <sys/stat.h>
#include <utime.h>

extern int sys_setup(void * BIOS);
extern int sys_exit(int error_code);
extern int sys_fork(void);
extern int sys_read(unsigned int fd, char * buf, int count);
extern int sys_write(unsigned int fd, char * buf, int count);
extern int sys_open(const char * filename, int flag, int mode);
extern int sys_close(unsigned int fd);
extern int sys_waitpid(pid_t pid, unsigned long * stat_addr, int options);
//extern int sys_creat();
extern int sys_link(const char * oldname, const char * newname);
extern int sys_unlink(const char * name);
extern int sys_execve(void);
extern int sys_chdir(const char * filename);
extern int sys_time(long * tloc);
//extern int sys_mknod();
//extern int sys_chmod();
//extern int sys_chown();
//extern int sys_break();
extern int sys_stat(char * filename, struct stat * statbuf);
//extern int sys_lseek();
extern int sys_getpid(void);
//extern int sys_mount();
//extern int sys_umount();
extern int sys_setuid(int uid);
extern int sys_getuid(void);
//extern int sys_stime();
//extern int sys_ptrace();
extern int sys_alarm(long seconds);
extern int sys_fstat(unsigned int fd, struct stat * statbuf);
//extern int sys_pause();
extern int sys_utime(char * filename, struct utimbuf * times);
//extern int sys_stty();
//extern int sys_gtty();
//extern int sys_access();
//extern int sys_nice();
//extern int sys_ftime();
extern int sys_sync(void);
extern int sys_kill(int pid, int sig);
//extern int sys_rename();
extern int sys_mkdir(const char * pathname, int mode);
extern int sys_rmdir(const char * name);
extern int sys_dup(unsigned int fildes);
extern int sys_pipe(unsigned long * fildes);
//extern int sys_times();
//extern int sys_prof();
//extern int sys_brk();
//extern int sys_setgid();
//extern int sys_getgid();
extern int sys_signal(int signum, long handler, long restorer);
extern int sys_geteuid(void);
extern int sys_getegid(void);
//extern int sys_acct();
//extern int sys_phys();
//extern int sys_lock();
extern int sys_ioctl(unsigned int fd, unsigned int cmd, unsigned long arg);
extern int sys_fcntl(unsigned int fd, unsigned int cmd, unsigned long arg);
//extern int sys_mpx();
//extern int sys_setpgid();
//extern int sys_ulimit();
//extern int sys_uname();
//extern int sys_umask();
//extern int sys_chroot();
//extern int sys_ustat();
//extern int sys_dup2();
extern int sys_getppid(void);
//extern int sys_getpgrp();
//extern int sys_setsid();
extern int sys_sigaction(int signum, const struct sigaction * action,
	struct sigaction * oldaction);
//extern int sys_sgetmask();
//extern int sys_ssetmask();
//extern int sys_setreuid();
//extern int sys_setregid();
//extern int sys_sigpending();
//extern int sys_sigsuspend();
//extern int sys_sethostname();
//extern int sys_setrlimit();
//extern int sys_getrlimit();
//extern int sys_getrusage();
//extern int sys_gettimeofday();
//extern int sys_settimeofday();
//extern int sys_getgroups();
//extern int sys_setgroups();
//extern int sys_select();
extern int sys_symlink(const char * oldname, const char * newname);
//extern int sys_lstat();
//extern int sys_readlink();
//extern int sys_uselib();
extern int sys_ls(void);
