#include <linux/sys.h>
#include <linux/sched.h>

fn_ptr sys_call_table[] = { 
    sys_setup,
    sys_exit,
    sys_fork,
    sys_read,
    sys_write,
    sys_open,
    sys_close,
    sys_waitpid,
    0,//    sys_creat,
    sys_link,

    sys_unlink,
    sys_execve,
    sys_chdir,
    sys_time,
    0,//    sys_mknod,
    0,//    sys_chmod,

    0,//    sys_chown,
    0,//    sys_break,
    sys_stat,
    0,//    sys_lseek,
    sys_getpid,
    0,//    sys_mount,

    0, //    sys_umount,
    sys_setuid,
    sys_getuid,
    0, //    sys_stime,
    0, //    sys_ptrace,
    sys_alarm,

    sys_fstat,
    0, //sys_pause,
    sys_utime,
    0,//    sys_stty,
    0,//    sys_gtty,
    0,//    sys_access,

    0,//    sys_nice,
    0,//    sys_ftime,
    sys_sync,
    sys_kill,
    0,//    sys_rename,
    sys_mkdir,

    sys_rmdir,
    sys_dup,
    sys_pipe,
    0,//    sys_times,
    0,//    sys_prof,
    0,//    sys_brk,
    0,//    sys_setgid,

    0,//    sys_getgid,
    sys_signal,
    sys_geteuid,
    sys_getegid,
    0,//    sys_acct,
    0,//    sys_phys,

    0, //    sys_lock,
    sys_ioctl,
    sys_fcntl,
    0, //    sys_mpx,
    0, //    sys_setpgid,
    0, //    sys_ulimit,

    0, //    sys_uname,
    0, //    sys_umask,
    0, //    sys_chroot,
    0, //    sys_ustat,
    0, //    sys_dup2,
    sys_getppid,

    0, //    sys_getpgrp,
    0, //    sys_setsid,
    sys_sigaction,
    0, //    sys_sgetmask,
    0, //    sys_ssetmask,

    0, //    sys_setreuid,
    0, //    sys_setregid,
    0, //    sys_sigsuspend,
    0, //    sys_sigpending,
    0, //    sys_sethostname,
    0, //    sys_setrlimit,
    0, //    sys_getrlimit,
    0, //    sys_getrusage,
    0, //    sys_gettimeofday,
    0, //    sys_settimeofday,
    0, //    sys_getgroups,
    0, //    sys_setgroups,
    0, //    sys_select,
    sys_symlink,
    0, //    sys_lstat,
    0, //    sys_readlink,
    0, //    sys_uselib
    sys_ls,
};

int NR_syscalls = sizeof(sys_call_table)/sizeof(fn_ptr);
